name: Build Step

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-push-docker-image:
    name: Build Docker image and push to registry
    runs-on: ubuntu-latest

    env:
      PORT: 3000
      POSTGRES_URL: ${{ secrets.POSTGRES_URL }}
      POSTGRES_URL_NON_POOLING: ${{ secrets.POSTGRES_URL_NON_POOLING }}
      NEXTAUTH_URL: https://menu-planner.rary.re/api/auth
      NEXTAUTH_SECRET: ${{ secrets.NEXTAUTH_SECRET}}
      GOOGLE_ID: ${{ secrets.GOOGLE_ID }}
      GOOGLE_SECRET: ${{ secrets.GOOGLE_SECRET }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Github Packages
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.PACKAGES }}

      - name: lowercase github.repository
        run: |
          echo "IMAGE_NAME=${GITHUB_REPOSITORY@L}" >> ${GITHUB_ENV}

      - name: Build image and push to Docker Hub and Github Container Registry
        uses: docker/build-push-action@v2
        with:
          context: ./
          tags: ghcr.io/${{ env.IMAGE_NAME }}:${{ github.sha }}
          push: ${{github.ref == 'refs/heads/main' }}

      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}