name: Build Step

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-push-docker-image:
    name: Build Docker image and push to registry
    runs-on: ubuntu-latest
    needs: ['build']

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Github Packages
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.PACKAGES }}

      - name: Build image and push to Docker Hub and Github Container Registry
        uses: docker/build-push-action@v2
        with:
          context: ./
          tags: /
            ghcr.io/Rar-files/${{ github.repository }}:${{ github.sha }}
          push: ${{github.ref == 'refs/heads/main' }}

      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}